//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointMed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int patientID { get; set; }
        public int scheduleID { get; set; }
        public string prescription { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
