version: '3.4'

services:
  appointmed:
    image: ${DOCKER_REGISTRY-}appointmed
    build:
<<<<<<< .mine
      context: .\AppointMed
=======
      context: .
>>>>>>> .theirs
      dockerfile: Dockerfile
      tty: true
